/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nogometnaliga;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author JakaKralj
 */
public class NogometnaLigaSwing extends javax.swing.JFrame {

    DefaultListModel<String> listModelEkipe = new DefaultListModel<>();
    DefaultListModel<String> listModelIgralci = new DefaultListModel<>();

    ArrayList<Ekipa> seznamEkip = new ArrayList<>();
    ArrayList<Igralec> seznamIgr = new ArrayList<>();

    public NogometnaLigaSwing() {
        initComponents();
        napolniSeznamEkip();
        napolniSeznamEkipCb(0);
        napolniSeznamIgralcev();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlEkipe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEkipe = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtNaslov = new javax.swing.JTextField();
        txtPosta = new javax.swing.JTextField();
        txtGlavniT = new javax.swing.JTextField();
        txtSteviloN = new javax.swing.JTextField();
        btnAddTeam = new javax.swing.JButton();
        btnEditTeam = new javax.swing.JButton();
        btnDeleteTeam = new javax.swing.JButton();
        pnlIgralci = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listIgralci = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIdPlayer = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPriimek = new javax.swing.JTextField();
        txtVisina = new javax.swing.JTextField();
        txtTeza = new javax.swing.JTextField();
        txtDavcnaS = new javax.swing.JTextField();
        txtNaslovIgralca = new javax.swing.JTextField();
        cmbEkipe = new javax.swing.JComboBox<>();
        btnAddPlayer = new javax.swing.JButton();
        btnEditPlayer = new javax.swing.JButton();
        btnDeletePlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEkipe.setBackground(new java.awt.Color(255, 255, 255));

        listEkipe.setModel(listModelEkipe);
        listEkipe.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEkipeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEkipe);

        jLabel1.setText("ID:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Naslov:");

        jLabel4.setText("Pošta:");

        jLabel5.setText("Glavni trener:");

        jLabel6.setText("Število naslovov:");

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtNaslov.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtPosta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtGlavniT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtSteviloN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnAddTeam.setBackground(new java.awt.Color(99, 71, 235));
        btnAddTeam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddTeam.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nogometnaliga/Slike/icons8-create-24.png"))); // NOI18N
        btnAddTeam.setText("Nova ekipa");
        btnAddTeam.setBorderPainted(false);
        btnAddTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeamActionPerformed(evt);
            }
        });

        btnEditTeam.setBackground(new java.awt.Color(43, 44, 52));
        btnEditTeam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditTeam.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nogometnaliga/Slike/icons8-edit-24.png"))); // NOI18N
        btnEditTeam.setText("Uredi ekipo");
        btnEditTeam.setBorderPainted(false);
        btnEditTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTeamActionPerformed(evt);
            }
        });

        btnDeleteTeam.setBackground(new java.awt.Color(228, 88, 88));
        btnDeleteTeam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteTeam.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nogometnaliga/Slike/icons8-remove-24.png"))); // NOI18N
        btnDeleteTeam.setText("Izbriši ekipo");
        btnDeleteTeam.setBorderPainted(false);
        btnDeleteTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEkipeLayout = new javax.swing.GroupLayout(pnlEkipe);
        pnlEkipe.setLayout(pnlEkipeLayout);
        pnlEkipeLayout.setHorizontalGroup(
            pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEkipeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEkipeLayout.createSequentialGroup()
                        .addComponent(btnAddTeam)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditTeam)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteTeam))
                    .addGroup(pnlEkipeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addGroup(pnlEkipeLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSteviloN))
                                .addGroup(pnlEkipeLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlEkipeLayout.createSequentialGroup()
                                .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEkipeLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEkipeLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)))
                                .addGap(12, 12, 12)
                                .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNaziv)
                                    .addComponent(txtNaslov)
                                    .addComponent(txtPosta)
                                    .addComponent(txtGlavniT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlEkipeLayout.setVerticalGroup(
            pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEkipeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEkipeLayout.createSequentialGroup()
                        .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGlavniT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSteviloN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditTeam)
                    .addGroup(pnlEkipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddTeam)
                        .addComponent(btnDeleteTeam)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ekipe", pnlEkipe);

        pnlIgralci.setBackground(new java.awt.Color(255, 255, 255));

        listIgralci.setModel(listModelIgralci);
        listIgralci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listIgralciValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listIgralci);

        jLabel7.setText("ID:");

        jLabel8.setText("Ime:");

        jLabel9.setText("Priimek:");

        jLabel10.setText("Visina:");

        jLabel11.setText("Teza:");

        jLabel12.setText("Davčna številka:");

        jLabel13.setText("Naslov:");

        jLabel14.setText("ID Ekipa:");

        txtIdPlayer.setEditable(false);
        txtIdPlayer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtIme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtPriimek.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtVisina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtTeza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtDavcnaS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtNaslovIgralca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        cmbEkipe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbEkipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddPlayer.setBackground(new java.awt.Color(99, 71, 235));
        btnAddPlayer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddPlayer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nogometnaliga/Slike/icons8-create-24.png"))); // NOI18N
        btnAddPlayer.setText("Nov igralec");
        btnAddPlayer.setBorderPainted(false);
        btnAddPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlayerActionPerformed(evt);
            }
        });

        btnEditPlayer.setBackground(new java.awt.Color(43, 44, 52));
        btnEditPlayer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditPlayer.setForeground(new java.awt.Color(255, 255, 255));
        btnEditPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nogometnaliga/Slike/icons8-edit-24.png"))); // NOI18N
        btnEditPlayer.setText("Uredi igralca");
        btnEditPlayer.setBorderPainted(false);
        btnEditPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlayerActionPerformed(evt);
            }
        });

        btnDeletePlayer.setBackground(new java.awt.Color(228, 88, 88));
        btnDeletePlayer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeletePlayer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletePlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nogometnaliga/Slike/icons8-remove-24.png"))); // NOI18N
        btnDeletePlayer.setText("Izbriši igralca");
        btnDeletePlayer.setBorderPainted(false);
        btnDeletePlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIgralciLayout = new javax.swing.GroupLayout(pnlIgralci);
        pnlIgralci.setLayout(pnlIgralciLayout);
        pnlIgralciLayout.setHorizontalGroup(
            pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIgralciLayout.createSequentialGroup()
                .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIgralciLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnEditPlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeletePlayer)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIgralciLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12)
                    .addGroup(pnlIgralciLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdPlayer)
                    .addComponent(txtIme)
                    .addComponent(txtPriimek)
                    .addComponent(txtVisina)
                    .addComponent(txtTeza)
                    .addComponent(txtDavcnaS)
                    .addComponent(txtNaslovIgralca)
                    .addComponent(cmbEkipe, 0, 150, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        pnlIgralciLayout.setVerticalGroup(
            pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIgralciLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIgralciLayout.createSequentialGroup()
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIdPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPriimek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtVisina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDavcnaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNaslovIgralca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEkipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeletePlayer)
                    .addGroup(pnlIgralciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddPlayer)
                        .addComponent(btnEditPlayer)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Igralci", pnlIgralci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listEkipeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEkipeValueChanged
        EkipaDaoImpl ekDao = new EkipaDaoImpl();

        String izbZapis = listEkipe.getSelectedValue();

        if (izbZapis != null && !izbZapis.equals("")) {
            int id = Integer.parseInt(izbZapis.substring(0, izbZapis.indexOf(":")));
            Ekipa ek = ekDao.getEkipaById(id);

            txtId.setText(String.valueOf(ek.getId()));
            txtNaziv.setText(String.valueOf(ek.getNaziv()));
            txtNaslov.setText(String.valueOf(ek.getNaslov()));
            txtPosta.setText(String.valueOf(ek.getPosta()));
            txtGlavniT.setText(String.valueOf(ek.getGlavni_trener()));
            txtSteviloN.setText(String.valueOf(ek.getStevilo_naslovov()));
        }
        napolniSeznamIgralcev();
    }//GEN-LAST:event_listEkipeValueChanged

    private void btnDeleteTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTeamActionPerformed
        EkipaDaoImpl ekDao = new EkipaDaoImpl();
        String izbZapis = listEkipe.getSelectedValue();

        if (izbZapis != null && !izbZapis.equals("")) {
            int id = Integer.parseInt(izbZapis.substring(0, izbZapis.indexOf(":")));
            /*
            IgralecDaoImpl igrDao = new IgralecDaoImpl();
            seznamIgr = igrDao.getAllIgralci();
            for (Igralec igr : seznamIgr) {
                if (igr.getIdEkipa() == id) {
                    Ekipa ek = new Ekipa();
                    EkipaDaoImpl ekDao = new EkipaDaoImpl();
                    ek = ekDao.getEkipaById(igr.getIdEkipa());
                    listModelIgralci.addElement(igr.getId() + ": " + igr.getIme() + ", " + igr.getPriimek() + ", " + igr.getVisina() + ", " + igr.getTeza() + ", " + igr.getDavcna_stevilka() + ", " + igr.getNaslov() + ", " + ek.getNaziv());
                }
            }
             */
            ekDao.deleteEkipa(id);
            napolniSeznamEkip();
            javax.swing.JOptionPane.showMessageDialog(this, "Ekipa " + txtNaziv.getText() + " je bila uspesno izbrisana.");
        }
    }//GEN-LAST:event_btnDeleteTeamActionPerformed

    private void btnAddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeamActionPerformed
        EkipaDaoImpl ekDao = new EkipaDaoImpl();

        Ekipa ek = new Ekipa(txtNaziv.getText(),
                txtNaslov.getText(), Integer.parseInt(txtPosta.getText()),
                txtGlavniT.getText(),
                Integer.parseInt(txtSteviloN.getText()));

        ekDao.insertEkipa(ek);
        napolniSeznamEkip();
        napolniSeznamEkipCb(0);
    }//GEN-LAST:event_btnAddTeamActionPerformed

    private void btnEditTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTeamActionPerformed
        EkipaDaoImpl ekDao = new EkipaDaoImpl();

        if (txtId.getText().equalsIgnoreCase("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Za urejanje podatkov ekipe izberite vsaj 1 ekipo.");
        } else {
            Ekipa ek = new Ekipa(Integer.parseInt(txtId.getText()), txtNaziv.getText(),
                    txtNaslov.getText(), Integer.parseInt(txtPosta.getText()),
                    txtGlavniT.getText(), Integer.parseInt(txtSteviloN.getText()));

            ekDao.updateEkipa(ek);
            napolniSeznamEkip();
            javax.swing.JOptionPane.showMessageDialog(this, "Ekipa " + txtNaziv.getText() + " je bila uspešno urejena.");
        }

    }//GEN-LAST:event_btnEditTeamActionPerformed

    private void btnAddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlayerActionPerformed
        IgralecDaoImpl igrDao = new IgralecDaoImpl();
        String izbCmbBox = cmbEkipe.getSelectedItem().toString();
        int id = Integer.parseInt(izbCmbBox.substring(0, izbCmbBox.indexOf(":")));

        Igralec igr = new Igralec(txtIme.getText(),
                txtPriimek.getText(), Integer.parseInt(txtVisina.getText()), Integer.parseInt(txtTeza.getText()),
                Integer.parseInt(txtDavcnaS.getText()),
                txtNaslovIgralca.getText(),
                id);

        igrDao.insertIgralec(igr);
        napolniSeznamIgralcev();
    }//GEN-LAST:event_btnAddPlayerActionPerformed

    private void btnEditPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlayerActionPerformed
        IgralecDaoImpl igrDao = new IgralecDaoImpl();
        String izbCmbBox = cmbEkipe.getSelectedItem().toString();
        int id = Integer.parseInt(izbCmbBox.substring(0, izbCmbBox.indexOf(":")));

        if (txtId.getText().equalsIgnoreCase("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Za urejanje podatkov igralca izberite vsaj 1 igralca.");
        } else {
            Igralec igr = new Igralec(Integer.parseInt(txtIdPlayer.getText()), txtIme.getText(),
                    txtPriimek.getText(), Integer.parseInt(txtVisina.getText()),
                    Integer.parseInt(txtTeza.getText()),
                    Integer.parseInt(txtDavcnaS.getText()),
                    txtNaslovIgralca.getText(), id);

            igrDao.updateIgralec(igr);
            javax.swing.JOptionPane.showMessageDialog(this, "Igralec " + txtIme.getText() + " " + txtPriimek.getText() + " je bil uspešno urejen.");
        }
        napolniSeznamIgralcev();
    }//GEN-LAST:event_btnEditPlayerActionPerformed

    private void btnDeletePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePlayerActionPerformed
        IgralecDaoImpl igrDao = new IgralecDaoImpl();
        String izbZapis = listIgralci.getSelectedValue();

        if (izbZapis != null && !izbZapis.equals("")) {
            int id = Integer.parseInt(izbZapis.substring(0, izbZapis.indexOf(":")));

            igrDao.deleteIgralec(id);
            napolniSeznamIgralcev();
            javax.swing.JOptionPane.showMessageDialog(this, "Igralec " + txtIme.getText() + " " + txtPriimek.getText() + " je bil uspesno izbrisan iz registra.");
        }
    }//GEN-LAST:event_btnDeletePlayerActionPerformed

    private void listIgralciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listIgralciValueChanged

        IgralecDaoImpl igrDao = new IgralecDaoImpl();
        
        String izbZapis = listIgralci.getSelectedValue();
         

        if (izbZapis != null && !izbZapis.equals("")) {
            int id = Integer.parseInt(izbZapis.substring(0, izbZapis.indexOf(":")));
            Igralec igr = igrDao.getIgralecById(id);
            Ekipa ek = new Ekipa();
            EkipaDaoImpl ekDao = new EkipaDaoImpl();
            ek = ekDao.getEkipaById(igr.getIdEkipa());
            String sestava = String.valueOf(igr.getIdEkipa()) + ": " + ek.getNaziv();
            txtIdPlayer.setText(String.valueOf(igr.getId()));
            txtIme.setText(String.valueOf(igr.getIme()));
            txtPriimek.setText(String.valueOf(igr.getPriimek()));
            txtVisina.setText(String.valueOf(igr.getVisina()));
            txtTeza.setText(String.valueOf(igr.getTeza()));
            txtDavcnaS.setText(String.valueOf(igr.getDavcna_stevilka()));
            txtNaslovIgralca.setText(String.valueOf(igr.getNaslov()));
            napolniSeznamEkipCbString(sestava);
        }
    }//GEN-LAST:event_listIgralciValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NogometnaLigaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NogometnaLigaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NogometnaLigaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NogometnaLigaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NogometnaLigaSwing().setVisible(true);
            }
        });

    }

    public void napolniSeznamEkip() {
        listModelEkipe.clear();
        EkipaDaoImpl ekDao = new EkipaDaoImpl();
        seznamEkip = ekDao.getAllEkipe();

        for (Ekipa ek : seznamEkip) {
            listModelEkipe.addElement(ek.getId() + ": " + ek.getNaziv() + ", " + ek.getNaslov() + ", " + ek.getPosta() + ", " + ek.getGlavni_trener() + ", " + ek.getStevilo_naslovov());
        }

        //listEkipe.setSelectedIndex(0);
    }

    public void napolniSeznamEkipCb(int idPrivzetaEkipa) {
        cmbEkipe.removeAllItems();
        EkipaDaoImpl ekDao = new EkipaDaoImpl();
        seznamEkip = ekDao.getAllEkipe();
        for (Ekipa ek : seznamEkip) {
            cmbEkipe.addItem(ek.getId() + ": " + ek.getNaziv());
        }
        //cmbEkipe.setSelectedIndex(idPrivzetaEkipa - 1);
        cmbEkipe.setSelectedItem(idPrivzetaEkipa);
    }
    
    public void napolniSeznamEkipCbString(String sestava) {
        cmbEkipe.removeAllItems();
        EkipaDaoImpl ekDao = new EkipaDaoImpl();
        seznamEkip = ekDao.getAllEkipe();
        for (Ekipa ek : seznamEkip) {
            cmbEkipe.addItem(ek.getId() + ": " + ek.getNaziv());
        }
        //cmbEkipe.setSelectedIndex(idPrivzetaEkipa - 1);
        cmbEkipe.getModel().setSelectedItem(sestava);
    }

    public void napolniSeznamIgralcev() {

        listModelIgralci.clear();
        IgralecDaoImpl igrDao = new IgralecDaoImpl();
        seznamIgr = igrDao.getAllIgralci();

        if (listEkipe.getSelectedValue() == null) {
            for (Igralec igr : seznamIgr) {
                Ekipa ek = new Ekipa();
                EkipaDaoImpl ekDao = new EkipaDaoImpl();
                ek = ekDao.getEkipaById(igr.getIdEkipa());
                listModelIgralci.addElement(igr.getId() + ": " + igr.getIme() + ", " + igr.getPriimek() + ", " + igr.getVisina() + ", " + igr.getTeza() + ", " + igr.getDavcna_stevilka() + ", " + igr.getNaslov() + ", " + ek.getNaziv());

            }
        } else {
            String izbZapis = listEkipe.getSelectedValue();
            int idEkipe = Integer.parseInt(izbZapis.substring(0, izbZapis.indexOf(":")));
            for (Igralec igr : seznamIgr) {
                if (igr.getIdEkipa() == idEkipe) {

                    Ekipa ek = new Ekipa();
                    EkipaDaoImpl ekDao = new EkipaDaoImpl();
                    ek = ekDao.getEkipaById(igr.getIdEkipa());
                    listModelIgralci.addElement(igr.getId() + ": " + igr.getIme() + ", " + igr.getPriimek() + ", " + igr.getVisina() + ", " + igr.getTeza() + ", " + igr.getDavcna_stevilka() + ", " + igr.getNaslov() + ", " + ek.getNaziv());
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlayer;
    private javax.swing.JButton btnAddTeam;
    private javax.swing.JButton btnDeletePlayer;
    private javax.swing.JButton btnDeleteTeam;
    private javax.swing.JButton btnEditPlayer;
    private javax.swing.JButton btnEditTeam;
    private javax.swing.JComboBox<String> cmbEkipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listEkipe;
    private javax.swing.JList<String> listIgralci;
    private javax.swing.JPanel pnlEkipe;
    private javax.swing.JPanel pnlIgralci;
    private javax.swing.JTextField txtDavcnaS;
    private javax.swing.JTextField txtGlavniT;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPlayer;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtNaslov;
    private javax.swing.JTextField txtNaslovIgralca;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPosta;
    private javax.swing.JTextField txtPriimek;
    private javax.swing.JTextField txtSteviloN;
    private javax.swing.JTextField txtTeza;
    private javax.swing.JTextField txtVisina;
    // End of variables declaration//GEN-END:variables
}
